
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.119:3306/test
    username: root
    password: 121121
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  thymeleaf:
    cache: false
    content-type: text/html
    charset:
    encoding: UTF-8
    mode: HTML5
  devtools:
    restart:
      additional-paths: src/main/java/


      restart:
        enabled: false
  http:
    multipart:
      enabled: true
      max-file-size: 500kb
      max-request-size: 200kb




spring.jpa.properties.dialect: org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
management:
  security:
    enabled: false
security:
  basic:
    enabled: true


spring.boot.admin.url: http://192.168.1.119:8090


# 消息队列的配置
spring.application.name: serverssssss
spring.rabbitmq.host: 192.168.1.119
spring.rabbitmq.port: 5672
spring.rabbitmq.username: fdh
spring.rabbitmq.password: fdh
spring.rabbitmq.virtual-host: /
spring.rabbitmq.publisher-confirms: true

#Tomcat的配置
server:
  connection-timeout:
  max-http-header-size: "8192"
  session:
    cookie:
      max-age:
      name: fdh
      http-only: true
      domain:
      path:
      secure:
      comment: 说明sss






